### ISSUE TITLE
Redirect loop in Chrome

### ISSUE THREAD

**Issue by kesal** [RNGR/Directus#716] opened 2015-03-17 17:09 UTC
After successful install (MAMP) Chrome is saying I'm in a redirect loop after trying ot log in.

**Comment by jwdeitch** [comment] 2015-03-17 17:34
What's your DIRECTUS_ENV in your config.php look like?

**Comment by kesal** [comment] 2015-03-17 17:34
define('DIRECTUS_ENV',  'development');

**Comment by cherryade** [comment] 2015-03-17 17:51
I am also having the problem.

**Comment by WellingGuzman** [comment] 2015-03-17 18:03
Hey @kesal, @cherryade I would like to know if this happened before or after logged in?

**Comment by cherryade** [comment] 2015-03-17 18:06
@WellingGuzman Just finished the installation, went back to the root, redirected me to projecthomelogin.php (assuming this is automatically created, or uses mod rewrite) and it has a redirect loop.

I tried removing/renaming the installation folder but no luck.

**Comment by WellingGuzman** [comment] 2015-03-17 18:21
@cherryade Would you mind removing cookies from that domain, and let me know if that would fix it for you.
I've experienced this before, and It was related to cookies.

But just after the installation is finish, it must redirect to to the login page. I would test it out?

By the way which branch did you use?

**Comment by kesal** [comment] 2015-03-17 18:27
Basically, as soon as I finished installation, it took me directly to the infinite looped page.

I'm viewing it on localhost:8888, using MAMP.

**Comment by cherryade** [comment] 2015-03-17 18:44
@WellingGuzman i tried resetting the cookies but still got the same error unfortunately.
fyi im using LAMPP on Ubuntu 12.04, with all dependencies.

Posted Via Mobile

**Comment by WellingGuzman** [comment] 2015-03-17 18:55
ok, I'm going to install Directus into another machine, to see how it goes.

Thanks for letting us know.

**Comment by kesal** [comment] 2015-03-17 20:07
any more info I can provide for you?  would love to get this up and running.

If it makes any difference, I'm connecting to a remote DB, NOT localhost

**Comment by cherryade** [comment] 2015-03-17 20:30
I would also love to get this up and running, however im connecting to a local database.

**Comment by WellingGuzman** [comment] 2015-03-18 11:22
What is you `DIRECTUS_PATH` value in the `config.php` file?

I'm trying to find the solution to this one, but I can't replicate the problem.

**Comment by cherryade** [comment] 2015-03-18 12:39
@WellingGuzman ah you got it! I had set the Project path to the path of my project rather than the path of the Directus installation as I thought that's what it meant, could be a little clearer with that.

I'm also inside Directus now, I chose not to install sample data, but I was wondering how I'd create a table? When I attempt to create one I get the following toast:
http://puu.sh/gFjMO/de437179cf.png

on the 'settings/tables' page. I've also tried creating a table manually and then attempting to add it, no luck.

**Comment by WellingGuzman** [comment] 2015-03-19 00:07
Great that you the issue is solved. @kesal do you still having issue with redirection loop?

This issue it seems to be related with this #719 #720 which seems to be related with permissions.

The query seems ok, does the user you are logged in has the permission to create tables?

**Comment by cherryade** [comment] 2015-03-19 10:41
@WellingGuzman Yup, I am currently logged in with the root user.

**Comment by cherryade** [comment] 2015-03-19 16:19
@WellingGuzman The problem was that `status_id` was not in the directus_privileges table. 

A few other suggestions: Allow dropping a column from table editing page;
Sort out navigation, sometimes it just adds a #settings for example to the end of the URL but does nothing, this is because I'd clicked on something beforehand which had put something on the URL.
When clicking the logo it takes me to mydomain.com/mydomain.com

**Comment by WellingGuzman** [comment] 2015-03-19 22:59
@cherryade Thanks for the suggestions.

I would take a look why directus_privileges didn't add that column on installation?

I'd close this as it seems that your problem is already fixed.

**Closed by WellingGuzman** 2015-03-19 22:59 UTC
Labels: urgent
