### ISSUE TITLE
Record Owner on tables permission

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/Directus#574] opened 2015-01-10 00:02 UTC
on `delete` permission I can delete all items regardless.

**Comment by benhaynes** [comment] 2015-01-15 14:43
@WellingGuzman For this, do you mean that when you change the permission to "delete" (or any other non-big permission) the permissions page would ask you for the owner column? This makes sense, though we'll have to figure out a good way to prompt the user. 

Maybe one of the directus alerts with a dropdown of fields in that table?

**Comment by benhaynes** [comment] 2015-03-08 20:47
@WellingGuzman What are you thinking for this one?

**Comment by WellingGuzman** [comment] 2015-03-09 08:09
This is awkward, I don't remember exactly why the title, is a bit of confusing, but what I meant, is that a user on `delete` permission, is allowed to delete all items regardless of being created by that user or not.

Now what you tried to say, what you mean because now I'm curious about ask for the owner column.

**Comment by benhaynes** [comment] 2015-05-06 00:58
@WellingGuzman So is there no delete (delete only your items) versus big-delete (delete anyone's items) permission? Only one type of delete permission? Why is that?

**Comment by benhaynes** [comment] 2015-08-17 16:01
@WellingGuzman I will close this as a duplicate of https://github.com/RNGR/Directus/issues/893 – basically you can delete anyone's items still. It would be nice however, if the permissions page warned you if you don't have a "record owner" column setup but choose allow_delete=1

**Closed by benhaynes** 2015-08-17 16:01 UTC
Labels: minor, optimization

**Comment by WellingGuzman** [comment] 2015-08-17 16:26
@benhaynes I think this is a great idea, would it be great to use #892 also on this one? as a popover?

**Comment by benhaynes** [comment] 2015-08-17 18:26
Yeah, that will be a good use of it! Nice to have these helper systems built in. But #892 also has the special ability to pull straight from a class/data-attribute so it's easy to setup more popup click events in the front-end.
