### ISSUE TITLE
Error Message when clicking on a Bookmark entry

### ISSUE THREAD

**Issue by Mahjouba91** [RNGR/Directus#1045] opened 2015-10-01 10:34 UTC
Hello,

I tried to create a bookmark, So I entered a name, and when I click on this new bookmark in the menu, I got this error message :

```
Server Error
Argument 1 passed to Directus\View\JsonView::render() must be of the type array, boolean given, called in C:\xampp\htdocs\Directus\api\api.php on line 798 and defined
```

**Comment by benhaynes** [comment] 2015-11-16 16:47
I haven't been able to reproduce this one, but my guess is that the Bookmark name was rejected. I think I remember an issue where bookmarks names couldn't start with numbers, or have special characters. Although I just tested this and had no errors. I'll close this as "can not reproduce" – anyone can re-open if it occurs again.

**Closed by benhaynes** 2015-11-16 16:47 UTC
Labels: 2. Critical

**Comment by benhaynes** [comment] 2015-11-16 16:50
I was just informed that this was most likely due to the Primary Key work being performed at the time of this error. We have since wrapped up this refactor and the issue should be resolved. Let us know if it persists.
